### ISSUE TITLE
Add the cabal-client library into the project using webpack

### ISSUE THREAD

**Issue by nikolaiwarner** [nikolaiwarner/react-cabal#2]
The next major step for this project is to bring in cabal-client (https://github.com/cabal-club/cabal-client). So far this has caused a lot of headaches due to the need to use webpack (because react native) and all of the dependencies of cabal-client.

**We need to find a path forward that allows us to use cabal-client along with the front end library of this repo that can be built for running on a browser and within react native (android & ios).** 

This issue just covers finding a way to get it building and functional on those targets. We'll cover actually integrating its features in other issues.

So far, we have a tidy setup using Expo and it'd be rad to be able to continue using it. However, if that's impossible, other configurations of connecting/smashing together a built version of cabal-client with this front end UI are cool too.

Also we probably want to focus on this branch of cabal-client as I think it's the one most ready for browser compatibility: https://github.com/cabal-club/cabal-client/tree/cabal-web

We've been sitting on some really amazing work in the cabal-client lib for too long. Once we're unblocked by this, we can really get our momentum back!

**Comment by nikolaiwarner** [comment]
@cblgh @RangerMauve @khubo

**Comment by RangerMauve** [comment]
One thing that's worked for me in the past is to use browserify bundles on the weird parts of the code (the stuff touching hyper, e.g.) and import that from Webpack.

Compiling with webpack itself is going to be extremely difficult because Webpack includes old versions of modules to polyfill stuff like `global.Buffer` which are missing methods that are getting used in cyrpto and networking code.

I've spent like a dozen hours trying to get `hyper-sdk` to compile with Webpack for the web in the [USHIN-DB](https://git.sr.ht/~breatheoutbreathein/ushin-db) repo before giving up and using Browserify, so if webpack was a hard requirement it might be possible to work off of the stuff there. 😅

**Comment by nikolaiwarner** [comment]
@RangerMauve _**Huge belated thank you for the suggestion to browserify cabal-client!!! 🔥🔥🔥**_ that seems be working well and has solved this issue for now within the browser! We'd still like to engage you for real with helping solve the similar issue on the react native side. I think we'll focus on getting the browser version stable first then reach out to you for that!

**Comment by RangerMauve** [comment]
Congrats! I'm currently working on getting hypercore-protocol stuff to work on mobile for [telios](https://github.com/RangerMauve/telios-mobile) and I think I'm pretty close to figuring it out. 😁 So once y'all are ready for react-native I think I'll be able to help a bunch there.
